row_filters:
  NONE:
    filter_sql_expr: |-
      True

rules:
  UNIQUE:
    rule_type: CUSTOM_SQL_STATEMENT
    params:
      custom_sql_statement: |-
        select $column from data
        group by $column
        having count(*) > 1

  FOREIGN_KEY_VALID:
    rule_type: CUSTOM_SQL_EXPR
    custom_sql_arguments:
      pk_dataset
      pk_table
      pk_column
    params:
      custom_sql_expr: |-
        $column in (select distinct $pk_column from $pk_dataset.`$pk_table`)

  ORDER_LINE_ITEMS_TOTAL:
    rule_type: CUSTOM_SQL_STATEMENT
    params:
      custom_sql_statement: |-
        select data.order_id, data.product_id, data.order_amount, totals.summed_amount from data
        join 
        (select order_id, sum(n_items * item_amount) as summed_amount
        from clouddq-pbalm.ecommerce.order_line_items
        group by order_id) as totals using (order_id)
        where not data.$column = totals.summed_amount

rule_bindings:
  FOREIGN_KEY_INVENTORY:
    entity_uri: bigquery://projects/clouddq-pbalm/datasets/ecommerce/tables/inventory
    column_id: product_id
    row_filter_id: NONE
    rule_ids:
        - FOREIGN_KEY_VALID:
            pk_dataset: ecommerce
            pk_table: catalog
            pk_column: product_id

  CATALOG_ID_UNIQUE:
    entity_uri: bigquery://projects/clouddq-pbalm/datasets/ecommerce/tables/catalog
    column_id: product_id
    row_filter_id: NONE
    rule_ids:
        - UNIQUE

  ORDER_LINE_ITEMS_TOTAL:
    entity_uri: bigquery://projects/clouddq-pbalm/datasets/ecommerce/tables/order_line_items
    column_id: order_amount
    row_filter_id: NONE
    rule_ids:
      - ORDER_LINE_ITEMS_TOTAL
